# Generated by Django 3.0.8 on 2020-09-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0002_auto_20200907_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedium',
            name='jobs',
            field=models.ManyToManyField(to='MainView.Job'),
        ),
    ]
