# Generated by Django 3.0.8 on 2020-09-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0003_sedium_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_title', models.CharField(max_length=200)),
                ('about_theme', models.TextField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('tickets', models.URLField()),
            ],
        ),
    ]
